### ISSUE TITLE
aws_recon: Loader job failed

### ISSUE THREAD

**Issue by danbryan** [OpenCSPM/opencspm#158]
I am trying to use my own AWS custom data but keep getting erros like
```
worker_1  | Loading /app/load_dir/combined_for_load.json
worker_1  | Loader job failed - TypeError nil is not a symbol nor a string (/app/app/jobs/lib/loader/asset/loaders/aws_loader/_resource_loader.rb:29:in `respond_to?')
worker_1  | Runner job failed - TypeError nil is not a symbol nor a string (/app/app/jobs/lib/loader/asset/loaders/aws_loader/_resource_loader.rb:29:in `respond_to?')
worker_1  | I, [2021-04-25T17:29:44.756110 #1]  INFO -- : [ActiveJob] [RunnerJob] [d0a242c6-7142-4601-8fcd-3249fcf0893a] Performed RunnerJob (Job ID: d0a242c6-7142-4601-8fcd-3249fcf0893a) from Sidekiq(default) in 180.72ms
```

I have made sure the manifest is correct, and if i paste the demo data content into the output.json it works.  However, when I create my own output.json with aws_recon I keep getting the loader job failed.

I am using custom format and output to newline delimited JSON

actually it seems to be related to specific components only, I was able to get it working by excluding the ones with errors. 

the following worked without errors.
```
aws_recon -x Route53Domains,Lambda,DirectoryService -l -r global,us-east-1 -f custom
```

Any ideas why these 3 services cause errors like..

for example if i remove Lambda...

```
aws_recon -x Route53Domains,DirectoryService -l -r global,us-east-1 -f custom
```

I get

```
worker_1  | Loader job failed - NoMethodError undefined method `vpc_id' for "{:subnet_ids=>[], :security_group_ids=>[], :vpc_id=>\"\"}":String (/app/app/jobs/lib/loader/asset/loaders/aws_loader/lambda.rb:18:in `function')
```

or if i removed DirectoryService 
```
aws_recon -x Route53Domains,Lambda -l -r global,us-east-1 -f custom
```

i get ...

```
worker_1  | Warning: no SecretsManager loader defined for asset type: secret
worker_1  | 
worker_1  | Warning: no SecretsManager loader defined for asset type: secret
worker_1  | Loader job failed - NameError uninitialized constant AWSLoader::DirectoryService (/app/app/jobs/lib/loader/asset/loaders/aws_loader/_resource_loader.rb:25:in `const_get')
worker_1  | Runner job failed - NameError uninitialized constant AWSLoader::DirectoryService (/app/app/jobs/lib/loader/asset/loaders/aws_loader/_resource_loader.rb:25:in `const_get')
worker_1  | I, [2021-04-25T19:10:46.936245 #1]  INFO -- : [ActiveJob] [RunnerJob] [a805f357-3064-493a-bc9c-12426f846be1] Performed RunnerJob (Job ID: a805f357-3064-493a-bc9c-12426f846be1) from Sidekiq(default) in 4959.08ms
```

I'v tried both the gem (aws_recon (0.5.7)), and docker (latest) for running aws_recon.

Any help would be appreciated.

**Comment by joshlarsen** [comment]
Hi @danbryan,

There are actually 2 different bugs happening here. One in aws_recon, and one in OpenCSPM. The one in OpenCSPM is clear. I will push an update for that shortly. For the aws_recon issue (related to Lambda), can you do the following:

```
cat output.json | grep '"asset_type":"function"' | jq
```

and paste the `vpc_config` field here? It looks like it's not getting mapped into a struct, which is what the loader is expecting.

**Comment by danbryan** [comment]
for the vpc_config looks like it can be either of these..
```
"vpc_config": "{:subnet_ids=>[\"subnet-12121212121212121\", \"subnet-12121212121212121\"], :security_group_ids=>[\"sg-12121212121212121\"], :vpc_id=>\"vpc-12121212121212121\"}",
```
or
```
"vpc_config": null,
```

**Comment by joshlarsen** [comment]
Ok, these should both be fixed now. You'll want to `docker-compose down` and then re-pull the `gcr.io/opencspm/engine:0.1.20` image before doing `docker-compose up` again.

For `aws_recon`, I bumped a new gem. So either upgrade the gem (`0.5.8`), or re-pull the `darkbitio/aws_recon:latest` image as well.

Thanks for raising these issues. Let me know how it goes.

**Comment by danbryan** [comment]
Thanks, Lambda now seems to work, however I am still having issues with Route53Domains, and DirectoryService

```
worker_1  | Loader job failed - NameError uninitialized constant AWSLoader::Route53Domains (/app/app/jobs/lib/loader/asset/loaders/aws_loader/_resource_loader.rb:25:in `const_get')
```

```
worker_1  | Loader job failed - NameError uninitialized constant AWSLoader::DirectoryService (/app/app/jobs/lib/loader/asset/loaders/aws_loader/_resource_loader.rb:25:in `const_get')
```

Let me know if there is anything i can do to help test.

**Comment by joshlarsen** [comment]
I did not see `Route53Domains` before. I've added that as well now. You'll need to re-pull the `gcr.io/opencspm/engine:0.1.20` image again.

Also, to make sure you're running with the new image, please make sure to remove the `core` volume:

```
docker-compose down
```

```
docker volume rm opencspm_core
```

```
docker-compose up
```

**Comment by danbryan** [comment]
Thanks, i updated the image and it now works!
